baseURL = 'https://sq8r.github.io/'
languageCode = 'en-us'
title = 'SQ8R BLOG - ham radio, fpv, 3d printing, arduino, electronics and more'

 [author]
   name = "Radek SQ8R"
   image = "profile.jpg"
   headline = "I'm who I am"
   bio = "In progress"
